### ISSUE TITLE
1.2 sürümü npm de yok

### ISSUE THREAD

**Issue by SadMap** [AtakanErmis/sozlukjs#23]
https://www.npmjs.com/package/sozlukjs ve build fail olduğundan publish tamamlanmamış

**Comment by AtakanErmis** [comment]
Bu proje artık maalesef geliştirilmemektedir. Kendi implementasyonunuzu yazmak gibi alternatif çözümlere başvurabilirsiniz. Ayrıca her türlü kişisel ve ticari projeleriniz bu repoyu forklayarak kendi değişikliklerinizi yapmakta özgürsünüz.
